### ISSUE TITLE
Package namespace conflicts with the SPDX Python tools

### ISSUE THREAD

**Issue by pombredanne** [bbqsrc/spdx-python#1]
Hi Brendan: 
I am the maintainer of the SPDX Python tools at https://github.com/spdx/tools-python and while this was a bit dormant we are restarting activity. You own the spdx name at Pypi and I have no issue with that, I will pick another package name for the tools proper. But one thing that would be great is if we can agree on sharing the `spdx` namespace for python modules which could mean some (minor) code changes here since you have some code in you `__init__.py`. Is that something you could consider? that would be very nice!

Alternatively we could also discuss joining forces... Your call.

**Comment by bbqsrc** [comment]
This code is already used in production with some tools in FreeBSD, so I can't make any changes to the package. It is also used by my lookup tool, [`spdx-lookup`](https://github.com/bbqsrc/spdx-lookup-python).

As it stands, this package is just a thin wrapper over the SPDX database, with some scripts run to clean up the broken formatting of several of the license documents (some have old Mac line endings, which makes absolutely no sense).

I would suggest you just use a separate namespace, like `spdx_tools`. There's already a large number of problems in the Python packaging world due to trying to work out which packages correspond to which import names, so I can't really support making that situation worse (I don't really maintain any other Python packages anymore for this reason).

That said, I can't (and won't) stop you from doing one of those `a.b.c`-style sub-packaging arrangements if you so choose, I just think it's one of the biggest issues with the Python packaging landscape as it stands. The API of this package is never going to change unless the SPDX database format changes, and the versioning follows exactly that of the SPDX database version.

> Alternatively we could also discuss joining forces... Your call.

Sure. As described, this package exists to be a minimal base for SPDX work, so I'm fine with discussing what you mean by this further.
